# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
# even-valued terms.

fib1 = 1
fib2 = 1

def increment_fibonacci():
	"""Increments fib1 to be fib2, and fib2 to be the next fib
	"""
	global fib1
	global fib2

	# fib3 used as temporary variable to hold the next fib
	fib3 = fib1 + fib2
	# assign fib1 & fib2, incrementing each
	fib1 = fib2
	fib2 = fib3


if __name__ == '__main__':
	total = 0

	# needs to be for less than 4 million
	while fib1 < 4000000:
		if fib1 % 2 == 0:
			total += fib1
		increment_fibonacci()

	print(total)